# Generated by Django 2.0.5 on 2018-05-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180524_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
