# Generated by Django 2.0.5 on 2018-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180524_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
